import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { applyCoverage, coverageTable } from "../src/render/readme.js";
import type { CoverageCounts } from "../src/render/readme.js";

// The README's figures, generated. Five hand-typed counts have shipped wrong in
// this repository — the `29` that should have been `56`, a note claiming two
// runtimes were unextracted, "168 passing" when it was 170, "262 passing" when
// it was 335, and a coverage list that was stale the sync after it was written.
// Correcting one by hand resets the clock; deriving it stops it.

const counts: CoverageCounts = {
  symbols: 3,
  modules: 2,
  official: 3,
  observed: 0,
  apiLevel: 1,
  described: 2,
  signature: 1,
  shapes: 1,
  properties: 4,
  declares: 1,
  declarations: 2,
  enums: 1,
  enumMembers: 5,
  members: 0,
  byRuntime: [["device-app", 3]],
  devices: 1,
  devicesWithLevel: 1,
  patterns: 0,
  examples: 0,
};

describe("coverageTable", () => {
  it("states where the numbers come from, inside the block", () => {
    // A reader who finds a stale-looking figure has to be able to tell whether
    // to edit it or re-run the render. The block says which.
    assert.match(coverageTable(counts, "en"), /Generated by `npm run render`/);
    assert.match(coverageTable(counts, "pt"), /Gerado por `npm run render`/);
  });

  it("carries no English in the translated table", () => {
    // One computation serves both READMEs, so a connector word baked into a
    // value rather than a label leaks across — `**513** in 50` did exactly that.
    const rows = coverageTable(counts, "pt")
      .split("\n")
      .filter((line) => line.startsWith("|") && !line.startsWith("| ---"));

    for (const row of rows) {
      const value = row.split("|")[2] ?? "";
      assert.doesNotMatch(value, /\b(in|of|and|with)\b/, `a label word leaked into ${row}`);
    }
  });

  it("renders every count it was given", () => {
    const table = coverageTable(counts, "en");

    assert.match(table, /\| Symbols \| \*\*3\*\* \|/);
    assert.match(table, /\| Modules \| 2 \|/);
    assert.match(table, /device-app 3/);
  });
});

describe("applyCoverage", () => {
  it("replaces only what lies between the markers", () => {
    const before = "# Title\n\nprose above\n\n<!-- coverage:start -->\nold\n<!-- coverage:end -->\n\nprose below\n";

    const after = applyCoverage(before, "<!-- coverage:start -->\nnew\n<!-- coverage:end -->");

    assert.ok(after);
    assert.match(after, /prose above/);
    assert.match(after, /prose below/);
    assert.match(after, /\nnew\n/);
    assert.doesNotMatch(after, /old/);
  });

  it("leaves a file with no markers alone rather than appending a block", () => {
    // A README that grows a second table on every render is worse than one that
    // never got the first, and the caller reports which file is not wired up.
    assert.equal(applyCoverage("# Title\n\nno markers here\n", "table"), undefined);
  });

  it("refuses a file whose markers are out of order", () => {
    const broken = "<!-- coverage:end -->\n<!-- coverage:start -->\n";

    assert.equal(applyCoverage(broken, "table"), undefined);
  });
});
