import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { describe, it } from "node:test";
import { escapeHtml, sitePage, siteStyles, syncDate } from "../src/render/site.js";
import type { CoverageCounts } from "../src/render/readme.js";
import type { SyncManifest } from "../src/types.js";

// The landing page. What is worth testing here is not the markup — that is
// checked by looking at it — but the two ways a generated page tells a reader
// something false: a figure that did not come from `data/`, and a translation
// that quietly fell back to the other language.

const counts: CoverageCounts = {
  symbols: 3,
  modules: 2,
  official: 3,
  observed: 0,
  apiLevel: 1,
  described: 2,
  signature: 1,
  shapes: 1,
  properties: 4,
  declares: 1,
  declarations: 2,
  enums: 1,
  enumMembers: 5,
  members: 0,
  byRuntime: [["device-app", 3]],
  devices: 1,
  devicesWithLevel: 1,
  patterns: 0,
  examples: 0,
};

const manifest: SyncManifest = {
  version: "0.2.0",
  lastSyncAt: "2026-09-22T20:25:03.762Z",
  sources: { "zeppos-docs": { commit: "c08725b2cfa3398d9e4da9379a2d83abaf3475a6" } },
  recordCounts: {},
};

describe("sitePage", () => {
  it("states where its numbers come from, on the page and in the source", () => {
    // A reader who finds a figure that looks stale has to be able to tell
    // whether to edit the page or re-run the render. Both say which.
    for (const language of ["en", "pt"] as const) {
      const page = sitePage(counts, manifest, language);
      assert.match(page, /Generated by `npm run render` from data\//);
      assert.match(page, /npm run render/);
    }
  });

  it("renders the counts it was given, not any of its own", () => {
    const page = sitePage(counts, manifest, "en");

    assert.match(page, /<span class="value">3<\/span><span class="label">symbols<\/span>/);
    assert.match(page, /<td>Modules<\/td><td>2<\/td>/);
    assert.match(page, /device-app 3/);
  });

  it("carries no English heading in the translated page", () => {
    // Two pages built from one template is exactly how a fallback goes
    // unnoticed: the page renders, it just renders in the wrong language.
    const page = sitePage(counts, manifest, "pt");
    const headings = [...page.matchAll(/<h[123][^>]*>(.*?)<\/h[123]>/g)].map((m) => m[1]);

    assert.ok(headings.length > 0, "the page rendered no headings at all");
    for (const heading of headings) {
      if (heading === "Zepp OS Agent Knowledge Base") continue; // the project's name
      assert.doesNotMatch(heading, /\b(How|What|Which|the|sources|keeps)\b/, `English in ${heading}`);
    }
  });

  it("links the other translation, both ways", () => {
    assert.match(sitePage(counts, manifest, "en"), /href="pt-BR\.html"/);
    assert.match(sitePage(counts, manifest, "pt"), /href="index\.html"/);
  });

  it("links each upstream source at the commit the manifest states", () => {
    // The footer is the page's provenance. A commit rendered as text is a
    // reader who cannot check what the numbers above it were extracted from.
    const page = sitePage(counts, manifest, "en");

    assert.match(
      page,
      /href="https:\/\/github\.com\/zepp-health\/zeppos-docs\/commit\/c08725b2cfa3398d9e4da9379a2d83abaf3475a6"/,
    );
    assert.match(page, /<code>c08725b<\/code>/);
  });

  it("names a source it has no repo for rather than dropping it", () => {
    // An unmapped source is still provenance. Silently omitting it would make
    // the page claim fewer sources than the base actually read.
    const page = sitePage(
      counts,
      { ...manifest, sources: { ...manifest.sources, "some-new-source": { commit: "abc1234" } } },
      "en",
    );

    assert.match(page, /some-new-source/);
  });

  it("renders the sync date only, so the bytes do not depend on where it ran", () => {
    // `lastSyncAt` is an instant. Through a locale or a zone, the same data
    // would render differently on another machine and the reproducibility check
    // in CI would fail on the timezone rather than on a real diff.
    const page = sitePage(counts, manifest, "en");

    assert.match(page, /2026-09-22/);
    assert.doesNotMatch(page, /20:25:03/);
  });

  it("teaches only commands package.json still defines", async () => {
    // The usage section is the one part of the page a reader will paste into a
    // terminal. A script renamed in package.json leaves the prose here saying
    // something that fails on the first line, and nothing else would catch it:
    // the render succeeds, the page looks right, the command is gone.
    const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf-8"));
    const defined = new Set(Object.keys(pkg.scripts ?? {}));

    for (const language of ["en", "pt"] as const) {
      const page = sitePage(counts, manifest, language);
      const taught = [...page.matchAll(/npm run ([a-z-]+)/g)].map((m) => m[1]);

      assert.ok(taught.length > 0, `the ${language} page teaches no command at all`);
      for (const script of taught) {
        assert.ok(defined.has(script), `the page teaches "npm run ${script}", which is not a script`);
      }
    }
  });

  it("does not open with a command that needs the network", () => {
    // data/ and the rendered pages are committed, so a clone already answers
    // questions. A setup block starting at `sync` would teach the opposite —
    // that the base needs a round trip and a cache before it says anything.
    const setup = /<pre><code>(git clone[\s\S]*?)<\/code><\/pre>/.exec(
      sitePage(counts, manifest, "en"),
    );

    assert.ok(setup, "the page shows no setup block");
    assert.doesNotMatch(setup[1], /npm run sync/);
    assert.match(setup[1], /npm install/);
  });

  it("states the three verdicts check answers with, including the two that are not failures", () => {
    // UNVERIFIABLE is the one a reader misreads as a failure, and VOUCHED is
    // the only one that means anything was actually backed. A page showing
    // VIOLATION alone would sell the tool as a linter, which it is not.
    const page = sitePage(counts, manifest, "pt");

    for (const verdict of ["VOUCHED", "UNVERIFIABLE", "VIOLATION"]) {
      assert.match(page, new RegExp(`<code>${verdict}</code>`));
    }
  });

  it("escapes what comes from the data", () => {
    const page = sitePage(
      counts,
      { ...manifest, version: '0.2.0"><script>' },
      "en",
    );

    assert.doesNotMatch(page, /<script>/);
    assert.match(page, /&quot;&gt;&lt;script&gt;/);
  });
});

describe("syncDate", () => {
  it("keeps the date and drops the time", () => {
    assert.equal(syncDate("2026-09-22T20:25:03.762Z"), "2026-09-22");
  });
});

describe("escapeHtml", () => {
  it("escapes the characters that would end an attribute or an element early", () => {
    assert.equal(escapeHtml('<a href="x">&'), "&lt;a href=&quot;x&quot;&gt;&amp;");
  });
});

describe("siteStyles", () => {
  it("defines every custom property it uses", () => {
    // A `var(--x)` with no `--x:` renders as nothing at all — an invisible
    // heading, not an error. The one class of CSS bug worth a test.
    const css = siteStyles();
    const defined = new Set([...css.matchAll(/^\s*(--[\w-]+):/gm)].map((m) => m[1]));

    for (const [, name] of css.matchAll(/var\((--[\w-]+)\)/g)) {
      assert.ok(defined.has(name), `${name} is used but never defined`);
    }
  });

  it("carries a dark variant for the whole palette", () => {
    // A page that defines half its palette per scheme reads as light text on a
    // light ground for anyone whose system is dark.
    const css = siteStyles();
    const dark = css.slice(css.indexOf("prefers-color-scheme: dark"));
    const light = css.slice(0, css.indexOf("prefers-color-scheme: dark"));

    for (const [, name] of light.matchAll(/^\s*(--[\w-]+):/gm)) {
      if (name === "--bg" || name === "--panel" || name === "--ink") {
        assert.match(dark, new RegExp(`${name}:`), `${name} has no dark value`);
      }
    }
  });
});
