import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { readDeviceFile, readExampleFiles, readModuleFiles, readPatternFiles } from "../store/read.js";
import type { Runtime, SymbolRecord } from "../types.js";

// The counts in the README, generated.
//
// This file exists because of a bug that has now shipped five times: a figure
// about the data, typed by hand into prose, that was true when it was written.
// The `29` that should have been `56`, the note claiming two runtimes were not
// extracted, "168 passing" when it was 170, "262 passing" when it was 335, and
// a coverage table that went stale twice in one afternoon. Each was corrected
// by hand, which is not a fix — it resets the clock.
//
// The rule the project already wrote for itself is "derive the figures that
// come from the data, or name the page to read instead of quoting it". This is
// the first half. The second half is prose: a sentence that quotes a number is
// rewritten to name the command or the page that prints it, and the numbers
// live only here.
//
// Written between markers rather than into a page of its own, because a README
// nobody can read end to end is worse than one with a generated block in it —
// and the reproducibility check in CI re-renders and fails on any diff, so a
// stale figure now breaks the build instead of misleading a reader.

const START = "<!-- coverage:start -->";
const END = "<!-- coverage:end -->";

/** Labels per README, so one computation serves both translations. */
const LABELS = {
  en: {
    lead: "Generated by `npm run render` from `data/`. Do not edit by hand — CI re-renders and fails on a diff.",
    metric: "What",
    count: "Count",
    symbols: "Symbols",
    modules: "Modules",
    official: "`OFFICIAL` / `OBSERVED`",
    apiLevel: "Symbols stating a minimum `API_LEVEL`",
    described: "Symbols with a description",
    signature: "Symbols with a call signature",
    shapes: "Symbols with a property table, and properties in them",
    declares: "Types declared under a heading with no name column",
    enums: "Value sets, and members in them",
    members: "Instance members",
    runtimes: "By runtime",
    devices: "Devices, of which run Zepp OS with a stated level",
    patterns: "Best-practice patterns",
    examples: "Sample apps read as code",
  },
  pt: {
    lead: "Gerado por `npm run render` a partir de `data/`. Não editar à mão — o CI re-renderiza e falha em qualquer diferença.",
    metric: "O quê",
    count: "Quantidade",
    symbols: "Símbolos",
    modules: "Módulos",
    official: "`OFFICIAL` / `OBSERVED`",
    apiLevel: "Símbolos que declaram `API_LEVEL` mínimo",
    described: "Símbolos com descrição",
    signature: "Símbolos com assinatura de chamada",
    shapes: "Símbolos com tabela de propriedades, e propriedades nelas",
    declares: "Tipos declarados sob um heading sem coluna de nome",
    enums: "Conjuntos de valores, e membros neles",
    members: "Membros de instância",
    runtimes: "Por runtime",
    devices: "Dispositivos, dos quais rodam Zepp OS com nível declarado",
    patterns: "Padrões de boas práticas",
    examples: "Apps de exemplo lidos como código",
  },
} as const;

export interface CoverageCounts {
  symbols: number;
  modules: number;
  official: number;
  observed: number;
  apiLevel: number;
  described: number;
  signature: number;
  shapes: number;
  properties: number;
  declares: number;
  declarations: number;
  enums: number;
  enumMembers: number;
  members: number;
  byRuntime: [Runtime, number][];
  devices: number;
  devicesWithLevel: number;
  patterns: number;
  examples: number;
}

const count = (records: SymbolRecord[], has: (r: SymbolRecord) => boolean): number =>
  records.filter(has).length;

export async function coverageCounts(dataDir: string): Promise<CoverageCounts> {
  const modules = await readModuleFiles(path.join(dataDir, "symbols"));
  const records = modules.flatMap((m) => m.symbols);
  const devices = await readDeviceFile(path.join(dataDir, "devices.json"));
  const patterns = await readPatternFiles(path.join(dataDir, "patterns"));
  const examples = await readExampleFiles(path.join(dataDir, "examples"));

  const byRuntime = new Map<Runtime, number>();
  for (const record of records) {
    for (const runtime of record.runtimes) byRuntime.set(runtime, (byRuntime.get(runtime) ?? 0) + 1);
  }

  return {
    symbols: records.length,
    modules: modules.length,
    official: count(records, (r) => r.confidence === "OFFICIAL"),
    observed: count(records, (r) => r.confidence === "OBSERVED"),
    apiLevel: count(records, (r) => r.minApiLevel !== undefined),
    described: count(records, (r) => r.description !== undefined),
    signature: count(records, (r) => r.signature !== undefined),
    shapes: count(records, (r) => (r.shapes?.length ?? 0) > 0),
    properties: records.reduce((n, r) => n + (r.shapes ?? []).reduce((m, s) => m + s.props.length, 0), 0),
    declares: count(records, (r) => (r.declares?.length ?? 0) > 0),
    declarations: records.reduce((n, r) => n + (r.declares?.length ?? 0), 0),
    enums: records.reduce((n, r) => n + (r.enums?.length ?? 0), 0),
    enumMembers: records.reduce((n, r) => n + (r.enums ?? []).reduce((m, e) => m + e.members.length, 0), 0),
    members: records.reduce((n, r) => n + (r.members?.length ?? 0), 0),
    byRuntime: [...byRuntime].sort((a, b) => b[1] - a[1]),
    devices: devices.length,
    devicesWithLevel: devices.filter((d) => d.runsZeppOs && d.latestApiLevel !== undefined).length,
    patterns: patterns.length,
    examples: examples.length,
  };
}

/** The block, as Markdown. Same table either side; only the labels differ. */
export function coverageTable(counts: CoverageCounts, language: keyof typeof LABELS): string {
  const label = LABELS[language];

  const rows: [string, string][] = [
    [label.symbols, `**${counts.symbols}**`],
    [label.modules, `${counts.modules}`],
    [label.official, `${counts.official} / ${counts.observed}`],
    [label.apiLevel, `${counts.apiLevel}`],
    [label.described, `${counts.described}`],
    [label.signature, `${counts.signature}`],
    [label.shapes, `${counts.shapes}, ${counts.properties}`],
    [label.declares, `${counts.declares}, ${counts.declarations}`],
    [label.enums, `${counts.enums}, ${counts.enumMembers}`],
    [label.members, `${counts.members}`],
    [label.runtimes, counts.byRuntime.map(([runtime, n]) => `${runtime} ${n}`).join(", ")],
    [label.devices, `${counts.devices}, ${counts.devicesWithLevel}`],
    [label.patterns, `${counts.patterns}`],
    [label.examples, `${counts.examples}`],
  ];

  return [
    START,
    "",
    `<!-- ${label.lead} -->`,
    "",
    `| ${label.metric} | ${label.count} |`,
    "| --- | --- |",
    ...rows.map(([what, value]) => `| ${what} | ${value} |`),
    "",
    END,
  ].join("\n");
}

/**
 * Replace the block between the markers, leaving the rest of the file alone.
 *
 * A file with no markers is left untouched and reported, rather than having a
 * block appended: a README that grows a table every render is worse than one
 * that never got it, and the caller can say which file is not wired up.
 */
export function applyCoverage(markdown: string, table: string): string | undefined {
  const start = markdown.indexOf(START);
  const end = markdown.indexOf(END);
  if (start < 0 || end < 0 || end < start) return undefined;

  return markdown.slice(0, start) + table + markdown.slice(end + END.length);
}

/** Rewrite the coverage block in each README that carries the markers. */
export async function renderReadmes(dataDir: string, outDir: string): Promise<{ written: string[] }> {
  const counts = await coverageCounts(dataDir);
  const written: string[] = [];

  for (const [file, language] of [
    ["README.md", "en"],
    ["README.pt-BR.md", "pt"],
  ] as const) {
    const target = path.join(outDir, file);
    let markdown: string;
    try {
      markdown = await readFile(target, "utf-8");
    } catch {
      continue;
    }

    const next = applyCoverage(markdown, coverageTable(counts, language));
    if (next === undefined || next === markdown) continue;

    await writeFile(target, next, "utf-8");
    written.push(file);
  }

  return { written };
}
